name: paulabrum
favicon: null
layout_spectrum: 0.40016
typography_spectrum: 0.58885
title: Paula Brum - Fotografia de Família
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8790a1'
    - '#000000'
    - '#232011'
    - '#555f71'
    - '#d5dbf5'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.9865479706786573
purpose: []
